# Generated by Django 5.1.1 on 2024-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.TextField(default='http://example.com/default_image.png'),
        ),
    ]
